### ISSUE TITLE
does not work with jQuery 1.4.4

### ISSUE THREAD

**Issue by jtnix** [zurb/joyride#121]
TypeError: b.replace is not a function: Line 19 of jquery-1.4.4.min.js

I see this also does not work with 1.5.2 and 1.7.something as well.
